name: macOS Build Only

on:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up and activate virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install FreeSimpleGUI matplotlib pandas pyinstaller
          pyinstaller --onefile --windowed macro_tracker_gui_clean.py
          mkdir release
          cp dist/macro_tracker_gui_clean release/MacroTracker
          cp *.csv release/
          cd release
          zip -r ../MacroTracker-macOS.zip ./*

      - name: Upload packaged zip
        uses: actions/upload-artifact@v2
        with:
          name: MacroTracker-macOS
          path: MacroTracker-macOS.zip



